sudo: required
language: generic
services: 
 - docker

 before_install:
 - docker build -t ammarmasood/docker-react -f Dockerfile.dev .
script: 
 - docker run -e CI=true ammarmasood/docker-react npm run test
